---
- block:

    - name: "Ensure existense of /tmp/vmutils-v{{ vmauth_version }}"
      ansible.builtin.file:
        path: "/tmp/vmutils-v{{ vmauth_version }}"
        mode: 0755
        state: directory

    - name: Unarchive vmutils binaries
      become: false
      unarchive:
        src: "{{ vmauth_repo_dir }}/vmutils-amd64-v{{ vmauth_version }}.tar.gz"
        dest: "/tmp/vmutils-v{{ vmauth_version }}"
        creates: "/tmp/vmutils-v{{ vmauth_version }}/vmauth-prod"
      check_mode: false

    - name: "Copy vmauth to {{ vmauth_install_dir }}"
      ansible.builtin.copy:
        src: "/tmp/vmutils-v{{ vmauth_version }}/vmauth-prod"
        dest: "{{ vmauth_install_dir }}/vmauth"
        owner: "{{ vmauth_system_user }}"
        group: "{{ vmauth_system_group }}"
        mode: 0755
        remote_src: yes
      notify: restart vmauth

- name: create vmauth configs directory
  file:
    path: "{{ vmauth_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
